import Head from 'next/head'
import Image from 'next/image'
import CategoriesList from '../components/CategoriesList';
import Footer from '../components/Footer';
import Header from '../components/Header';
import PostList from '../components/PostList';
import { useAuth } from '../lib/auth';
import { getCategories, getPosts } from "../lib/bloggrs-sdk";

export async function getServerSideProps(context) {
    const posts = await getPosts();
    const categories = await getCategories();
    return {
        props: {
            posts, categories
        }
    }
}

export default function Home({ posts, categories }) {
  // return "DSADA"
  return (
    <div className='flex-grid'>
      <div className='col-offset-2 col-4'>
        <PostList posts={posts} />
      </div>
      <div className='col-offset-1 col-2 row-offset-1'>
        <CategoriesList categories={categories}/>
      </div>
    </div>
  )
}

// export default function Home() {
//   const auth = useAuth();
//   let body_content = auth.user ? (
//     <div>
//       <p>Email: {auth.user.email}</p>
//       <button onClick={(e) => auth.signout()}>Sign out</button>
//     </div>
//   ) : (
//     <button onClick={e => auth.signin()}>Sign in</button>
//   )
//   return (
//     <>
//       <Head>mode
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       {body_content}
//   </>
//   )
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//         <script src="http://localhost:4444/dist/bloggrs.umd.js"></script>
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
